### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by kishorv06** [heinrichreimer/material-intro#257] opened 2018-08-27 15:35 UTC
App is crashing with data binding issue.

` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/heinrichreimersoftware/materialintro/databinding/MiActivityIntroBinding;`

**Comment by chimbori** [comment] 2018-09-08 19:29
Dupe of #256

**Closed** 2019-09-14 19:33 UTC
