### ISSUE TITLE
Error in new version 1.5.1

### ISSUE THREAD

**Issue by Spiderbezno** [HeinrichReimer/material-intro#61] opened 2016-05-31 06:56 UTC
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.heinrichreimersoftware.materialintro.slide.SlideAdapter.getSlide(SlideAdapter.java:69)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.getSlide(IntroActivity.java:756)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.updateParallax(IntroActivity.java:568)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.access$700(IntroActivity.java:52)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity$IntroPageChangeListener.onPageScrolled(IntroActivity.java:854)
       at com.heinrichreimersoftware.materialintro.view.FadeableViewPager$OnPageChangeListenerWrapper.onPageScrolled(FadeableViewPager.java:66)
       at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1850)
       at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1824)
       at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1762)
       at android.support.v4.view.ViewPager.computeScroll(ViewPager.java:1722)
       at android.view.View.updateDisplayListIfDirty(View.java:15167)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
       at android.view.View.updateDisplayListIfDirty(View.java:15140)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
       at android.view.View.updateDisplayListIfDirty(View.java:15140)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
       at android.view.View.updateDisplayListIfDirty(View.java:15140)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
       at android.view.View.updateDisplayListIfDirty(View.java:15140)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
       at android.view.View.updateDisplayListIfDirty(View.java:15140)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
       at android.view.View.updateDisplayListIfDirty(View.java:15140)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Sleeper9** [comment] 2016-05-31 07:00
This must be the same as #59

**Comment by Spiderbezno** [comment] 2016-05-31 07:07
Oh yes, only that i hhave 5 slides

El 31 may. 2016 9:00 a. m., László Illés <notifications@github.com> escribió:This must be the same as #59

**Comment by HeinrichReimer** [comment] 2016-05-31 08:11
Duplicate of #59

**Closed by HeinrichReimer** 2016-05-31 08:11 UTC
Labels: duplicate
