### ISSUE TITLE
import com.heinrichreimersoftware.materialintro.demo.databinding.FragmentLoginBinding;

### ISSUE THREAD

**Issue by susanlama1bsccsit** [heinrichreimer/material-intro#207] opened 2017-05-22 04:50 UTC
I didn't find this package file ?

**Comment by heinrichreimer** [comment] 2017-05-27 10:33
This issue is a duplicate of #198. Please make sure to check if the issue was already answered before posting a new issue.

**Closed by heinrichreimer** 2017-05-27 10:33 UTC
