### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by antonpit** [HeinrichReimer/material-intro#106] opened 2016-07-31 06:24 UTC
```
android.support.v4.view.ViewPager.fakeDragBy (ViewPager.java:2608)
com.heinrichreimersoftware.materialintro.app.IntroActivity.fakeDragToPosition (IntroActivity.java:346)
com.heinrichreimersoftware.materialintro.app.IntroActivity.onAnimationUpdate (IntroActivity.java:327)
android.animation.ValueAnimator.animateValue (ValueAnimator.java:1166)
android.animation.ValueAnimator.animationFrame (ValueAnimator.java:1102)
android.animation.ValueAnimator.doAnimationFrame (ValueAnimator.java:1131)
android.animation.ValueAnimator$AnimationHandler.doAnimationFrame (ValueAnimator.java:616)
android.animation.ValueAnimator$AnimationHandler.run (ValueAnimator.java:639)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:776)
android.view.Choreographer.doCallbacks (Choreographer.java:579)
android.view.Choreographer.doFrame (Choreographer.java:547)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:762)
android.os.Handler.handleCallback (Handler.java:800)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:194)
android.app.ActivityThread.main (ActivityThread.java:5371)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:833)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:600)
dalvik.system.NativeStart.main (NativeStart.java)
```

**Comment by HeinrichReimer** [comment] 2016-07-31 10:17
It would be useful if you send me the *full* log output.
Also note that it's hard to work on bugs that don't have any description on how you can reproduce the behavior.
Please add some additional information ASAP so that I can fix it.

**Comment by antonpit** [comment] 2016-07-31 10:47
Hi, 
sorry but this all information that I have, because i got this crash from crashlytics.

**Comment by HeinrichReimer** [comment] 2016-08-13 20:23
I'm sorry but I can't find any firing method in this log. Make sure that you paste the whole **raw** bug report from crashlytics here especially including the original `Exception` and **all** `Caused by`-clauses!

I'll close this issue until I get more detailed information from you as I can't use this log to find an error.

**Closed by HeinrichReimer** 2016-08-13 20:23 UTC
Labels: bug, high priority
