### ISSUE TITLE
setSkipEnabled and setFinishEnabled are not available

### ISSUE THREAD

**Issue by AkshayChordiya** [HeinrichReimer/material-intro#18] opened 2016-03-04 17:10 UTC
Both of the methods said above are mentioned in the documentation or Readme of this library. But they are not actually present.

I hope this issue is resolved soon as I'm waiting to use this library.

**Comment by HeinrichReimer** [comment] 2016-03-04 22:53
Duplicate of #13

**Closed by HeinrichReimer** 2016-03-04 22:53 UTC
Labels: duplicate
