### ISSUE TITLE
how can i change color of circle indicator ?

### ISSUE THREAD

**Issue by mahmooddagga** [HeinrichReimer/material-intro#44] opened 2016-04-21 12:43 UTC
how can i change color of circle indicator  or change shape ..

**Comment by HeinrichReimer** [comment] 2016-04-21 14:15
Duplicate of #39

**Closed by HeinrichReimer** 2016-04-21 14:15 UTC
Labels: duplicate

**Comment by wbervoets** [comment] 2016-07-01 06:26
Hi, 

The automatic coloring is not satisfying. Is there a way to override the color of the circle indicator?

I want to have a 
- white background for fragment
- white background where the indicator and buttons appear
- orange selected circle indicator
- lighter orange deselected circle indicator

I can almost get there except that the selecte circle color is white and the deselected circle indicator is orange.

Any ideas?
Thanks
Wim


Wim
