### ISSUE TITLE
Add option to completely hide skip and finish buttons

### ISSUE THREAD

**Issue by mahmooddagga** [HeinrichReimer/material-intro#43] opened 2016-04-21 12:41 UTC
how can i hide skip and finish button ???

i want to hide it in all pages .....

i tried 
        /* Enable/disable skip button */
        setSkipEnabled(false);

        /* Enable/disable finish button */
        setFinishEnabled(false);

i think its not working ,, it visible but not enable

**Comment by HeinrichReimer** [comment] 2016-04-21 14:19
Possible duplicate of #3 
Please attach a screenshot of the issue, so that I can better understand it.

**Comment by mahmooddagga** [comment] 2016-04-21 15:45
setSkipEnabled(false);
its only hide from first page ..

i want to hide  all button in all pages .....
skip back finish ...

and thanks

**Comment by mahmooddagga** [comment] 2016-04-21 16:49
i think it can be done quickly ,, set visibility gone for (skip ,back ,finish, next)

thank you very much ,,  i am waiting for new release ,, i hope it soon

**Comment by mahmooddagga** [comment] 2016-04-23 12:50
also if we can hide circular indicator in specific page or last page , will be great

**Comment by HeinrichReimer** [comment] 2016-04-26 16:20
So you basically want to hide the buttons at all?

**Comment by mahmooddagga** [comment] 2016-04-26 16:22
yes , thank for great library

**Closed** 2016-05-24 14:04 UTC
Labels: enhancement

**Comment by HeinrichReimer** [comment] 2016-05-24 14:09
Use the new methods `setButtonBackVisible()` and `setButtonNextVisible()`.
