### ISSUE TITLE
Attempt to invoke virtual method 'void android.view.VelocityTracker.addMovement(android.view.MotionEvent)' on a null object reference

### ISSUE THREAD

**Issue by wbervoets** [HeinrichReimer/material-intro#149] opened 2016-11-04 10:05 UTC
Crash report on Samsung SM-J320M

android.support.v4.view.ViewPager.fakeDragBy (ViewPager.java:2616)
com.heinrichreimersoftware.materialintro.app.IntroActivity$5.fakeDragToPosition (IntroActivity.java:349)
com.heinrichreimersoftware.materialintro.app.IntroActivity$5.onAnimationUpdate (IntroActivity.java:330)
android.animation.ValueAnimator.animateValue (ValueAnimator.java:1374)
android.animation.ValueAnimator.animationFrame (ValueAnimator.java:1298)
android.animation.ValueAnimator.doAnimationFrame (ValueAnimator.java:1339)
android.animation.ValueAnimator$AnimationHandler.doAnimationFrame (ValueAnimator.java:715)
android.animation.ValueAnimator$AnimationHandler.run (ValueAnimator.java:738)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:829)
android.view.Choreographer.doCallbacks (Choreographer.java:606)
android.view.Choreographer.doFrame (Choreographer.java:575)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:815)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6934)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)

Any idea?

Thanks
wim

**Comment by HeinrichReimer** [comment] 2016-12-08 02:26
Duplicate of #148

**Closed by HeinrichReimer** 2016-12-08 02:26 UTC
Labels: bug, duplicate
